services:
  - type: web
    name: lacasitadevero
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        value: shuttle.proxy.rlwy.net
      - key: DB_NAME
        value: LaCasitaDeVero
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: anJkMDnhTJoXaMDjgYFpfmkMBUskRZFu
      - key: DB_PORT
        value: 21840
